name: CacheURL

on:
  workflow_dispatch:

jobs:
  lessThan:
    name: CacheURL
    runs-on: ubuntu-latest
#     env:
#       ACTIONS_CACHE_URL: this is url
#       ACTIONS_RUNTIME_URL: django
    steps:
#         - name: Activate Cache
#           uses: actions/cache@v3
        - run: env
        - run: echo $ACTIONS_CACHE_URL
        - run: echo $ACTIONS_RUNTIME_URL
