name: Invalid Chars

on:
  workflow_dispatch:

jobs:
  lessThan:
    name: tango-django
    runs-on: ubuntu-latest

    steps:
        - name: Harden Runner
          uses: step-security/harden-runner@v1.4.5
        - run: whoami
